"""
Manual Calendar Adapter

Reads economic events from local JSON file instead of paid API.
Works with calendar generated by calendar_generator.py

This is FREE and reliable - no API needed!
"""

import json
import logging
from typing import List, Optional
from datetime import datetime, timedelta
from pathlib import Path
from dataclasses import dataclass

logger = logging.getLogger(__name__)


@dataclass
class CalendarEvent:
    """Economic calendar event from JSON file"""
    date: str  # YYYY-MM-DD
    time_utc: str  # HH:MM
    event: str  # Short code (NFP, CPI, etc.)
    description: str  # Full description
    country: str  # US, UK, EU
    importance: str  # high, medium, low
    block_minutes_before: int = 15
    block_minutes_after: int = 15
    
    @property
    def datetime_utc(self) -> datetime:
        """Get event as datetime object"""
        return datetime.strptime(
            f"{self.date} {self.time_utc}",
            "%Y-%m-%d %H:%M"
        )
    
    def is_high_impact(self) -> bool:
        """Check if high impact"""
        return self.importance == "high"
    
    def minutes_until_event(self, current_time: datetime) -> int:
        """Calculate minutes until event"""
        delta = self.datetime_utc - current_time
        return int(delta.total_seconds() / 60)


class ManualCalendarAdapter:
    """
    Manual calendar adapter - reads from local JSON file
    
    Replaces paid Trading Economics API ($300-500/month)
    
    Usage:
    1. Generate calendar: python -m src.data.calendar_generator
    2. Verify CPI dates on investing.com
    3. Use this adapter to check event blocking
    
    Maintenance: Regenerate calendar monthly (5 minutes)
    """
    
    def __init__(
        self,
        calendar_file: str = "data/economic_calendar.json",
        filter_countries: List[str] = None
    ):
        """
        Initialize manual calendar
        
        Args:
            calendar_file: Path to JSON calendar
            filter_countries: Optional country filter
        """
        self.calendar_file = Path(calendar_file)
        self.filter_countries = filter_countries or ['US', 'UK', 'EU']
        self.events: List[CalendarEvent] = []
        self._load_calendar()
    
    def _load_calendar(self):
        """Load events from JSON file"""
        if not self.calendar_file.exists():
            logger.warning(f"Calendar file not found: {self.calendar_file}")
            logger.info(f"Generate calendar with: python -m src.data.calendar_generator")
            return
        
        try:
            with open(self.calendar_file, 'r') as f:
                data = json.load(f)
            
            raw_events = data.get('events', [])
            
            for event_dict in raw_events:
                # Filter by country
                if event_dict.get('country') not in self.filter_countries:
                    continue
                
                # Create CalendarEvent
                event = CalendarEvent(
                    date=event_dict['date'],
                    time_utc=event_dict['time_utc'],
                    event=event_dict['event'],
                    description=event_dict['description'],
                    country=event_dict['country'],
                    importance=event_dict.get('importance', 'high'),
                    block_minutes_before=event_dict.get('block_minutes_before', 15),
                    block_minutes_after=event_dict.get('block_minutes_after', 15)
                )
                
                self.events.append(event)
            
            logger.info(f"Loaded {len(self.events)} events from {self.calendar_file}")
            
        except Exception as e:
            logger.error(f"Failed to load calendar: {e}")
    
    def get_events_in_range(
        self,
        start_time: datetime,
        end_time: datetime,
        high_impact_only: bool = True
    ) -> List[CalendarEvent]:
        """
        Get events within time range
        
        Args:
            start_time: Start datetime (UTC)
            end_time: End datetime (UTC)
            high_impact_only: Filter to high impact only
        
        Returns:
            List of events
        """
        events_in_range = []
        
        for event in self.events:
            event_time = event.datetime_utc
            
            if start_time <= event_time <= end_time:
                if high_impact_only and not event.is_high_impact():
                    continue
                
                events_in_range.append(event)
        
        return events_in_range
    
    def is_blocked(
        self,
        current_time: datetime,
        custom_block_before: Optional[int] = None,
        custom_block_after: Optional[int] = None
    ) -> tuple[bool, Optional[CalendarEvent]]:
        """
        Check if trading should be blocked at current time
        
        Args:
            current_time: Current datetime (UTC)
            custom_block_before: Override block_minutes_before
            custom_block_after: Override block_minutes_after
        
        Returns:
            (is_blocked, event) - True if blocked with event details
        """
        for event in self.events:
            event_time = event.datetime_utc
            
            # Use custom or event-specific block windows
            before = custom_block_before or event.block_minutes_before
            after = custom_block_after or event.block_minutes_after
            
            block_start = event_time - timedelta(minutes=before)
            block_end = event_time + timedelta(minutes=after)
            
            if block_start <= current_time <= block_end:
                return True, event
        
        return False, None
    
    def get_next_event(
        self,
        current_time: datetime,
        high_impact_only: bool = True
    ) -> Optional[CalendarEvent]:
        """
        Get next upcoming event
        
        Args:
            current_time: Current datetime (UTC)
            high_impact_only: Filter to high impact only
        
        Returns:
            Next event or None
        """
        upcoming = []
        
        for event in self.events:
            event_time = event.datetime_utc
            
            if event_time > current_time:
                if high_impact_only and not event.is_high_impact():
                    continue
                
                upcoming.append(event)
        
        if not upcoming:
            return None
        
        # Return soonest
        return min(upcoming, key=lambda e: e.datetime_utc)
    
    def fetch_calendar(
        self,
        start_date: Optional[datetime] = None,
        end_date: Optional[datetime] = None,
        force_refresh: bool = False
    ) -> List[CalendarEvent]:
        """
        Fetch calendar events (compatibility method for EventBlocker)
        
        Args:
            start_date: Start datetime (UTC)
            end_date: End datetime (UTC)
            force_refresh: Ignored (no API to refresh)
        
        Returns:
            List of calendar events
        """
        # Default date range: next 7 days
        if start_date is None:
            start_date = datetime.utcnow()
        if end_date is None:
            end_date = start_date + timedelta(days=7)
        
        return self.get_events_in_range(start_date, end_date, high_impact_only=False)
    
    def get_calendar_summary(self) -> dict:
        """Get summary of loaded calendar"""
        if not self.events:
            return {
                'status': 'empty',
                'events_loaded': 0,
                'message': 'Generate calendar with: python -m src.data.calendar_generator'
            }
        
        # Count by event type
        event_counts = {}
        for event in self.events:
            event_counts[event.event] = event_counts.get(event.event, 0) + 1
        
        # Get date range
        dates = [e.datetime_utc for e in self.events]
        
        return {
            'status': 'ready',
            'events_loaded': len(self.events),
            'event_types': event_counts,
            'earliest_event': min(dates).isoformat() if dates else None,
            'latest_event': max(dates).isoformat() if dates else None,
            'calendar_file': str(self.calendar_file)
        }


# Example usage
if __name__ == "__main__":
    import sys
    
    logging.basicConfig(level=logging.INFO)
    
    # Initialize
    calendar = ManualCalendarAdapter("data/economic_calendar.json")
    
    # Get summary
    summary = calendar.get_calendar_summary()
    print("\n" + "=" * 60)
    print("Manual Calendar Status")
    print("=" * 60)
    print(f"Status: {summary['status']}")
    print(f"Events loaded: {summary.get('events_loaded', 0)}")
    
    if summary['status'] == 'ready':
        print(f"\nEvent types:")
        for event_type, count in summary['event_types'].items():
            print(f"  {event_type}: {count}")
        
        # Check if currently blocked
        current_time = datetime.utcnow()
        is_blocked, event = calendar.is_blocked(current_time)
        
        print(f"\n{'-' * 60}")
        print("Current Status")
        print("-" * 60)
        
        if is_blocked:
            print(f"⛔ BLOCKED: {event.event} - {event.description}")
            print(f"   Time: {event.datetime_utc.isoformat()}")
        else:
            print("✅ Trading allowed")
        
        # Get next event
        next_event = calendar.get_next_event(current_time)
        if next_event:
            mins_until = next_event.minutes_until_event(current_time)
            print(f"\n📅 Next event: {next_event.event} in {mins_until} minutes")
            print(f"   {next_event.description}")
            print(f"   {next_event.datetime_utc.isoformat()}")
        print()
    else:
        print(f"\n{summary.get('message', '')}")
        print()
    
    sys.exit(0 if summary['status'] == 'ready' else 1)
