#!/usr/bin/env python3
"""
Test Signal Generation Using Saved Signals
Analyzes actual signals generated by the bot to verify logic correctness
"""

import json
import sys
from pathlib import Path
from datetime import datetime

# Add src to path
sys.path.insert(0, '/Users/kirtanbhatt/code/stockScreener/cloud-function')


def load_signals(signal_file: str):
    """Load signals from JSONL file"""
    signals = []
    with open(signal_file, 'r') as f:
        for line in f:
            if line.strip():
                signals.append(json.loads(line))
    return signals


def validate_signal(signal: dict, signal_num: int):
    """
    Validate a single signal's logic and calculations
    
    Signal generation rules:
    SELL: supertrend_direction == -1 AND price < ema AND (death_cross OR sma_fast < sma_slow)
    BUY: supertrend_direction == 1 AND price > ema AND (golden_cross OR sma_fast > sma_slow)
    """
    print(f"\n{'='*80}")
    print(f"Signal #{signal_num}: {signal['signal']} @ {signal['timestamp']}")
    print(f"{'='*80}")
    
    # Extract values
    price = signal['price']
    direction = signal['signal']
    sl = signal['sl']
    tp = signal['tp']
    indicators = signal['indicators']
    
    supertrend_dir = indicators['supertrend_direction']
    sma_fast = indicators['sma_fast']
    sma_slow = indicators['sma_slow']
    ema = indicators['ema']
    atr = indicators['atr']
    death_cross = indicators.get('death_cross', False)
    golden_cross = indicators.get('golden_cross', False)
    
    # Display signal details
    print(f"\n📊 Signal Data:")
    print(f"   Direction: {direction}")
    print(f"   Price: {price:.2f}")
    print(f"   Stop Loss: {sl:.2f}")
    print(f"   Take Profit: {tp:.2f}")
    print(f"   Strategy: {signal.get('strategy', 'N/A')}")
    
    print(f"\n📈 Indicators:")
    print(f"   Supertrend Direction: {'UPTREND (1)' if supertrend_dir == 1 else 'DOWNTREND (-1)'}")
    print(f"   SMA Fast: {sma_fast:.2f}")
    print(f"   SMA Slow: {sma_slow:.2f}")
    print(f"   EMA: {ema:.2f}")
    print(f"   ATR: {atr:.4f}")
    print(f"   Death Cross: {death_cross}")
    print(f"   Golden Cross: {golden_cross}")
    
    # Validate signal conditions
    print(f"\n✅ Condition Checks:")
    
    errors = []
    warnings = []
    
    if direction == 'SELL':
        # SELL signal validation
        print(f"   Supertrend Check: {supertrend_dir} == -1? {'✅' if supertrend_dir == -1 else '❌'}")
        if supertrend_dir != -1:
            errors.append("SELL signal but supertrend is not DOWNTREND")
        
        print(f"   Price vs EMA: {price:.2f} < {ema:.2f}? {'✅' if price < ema else '❌'}")
        if price >= ema:
            errors.append(f"SELL signal but price ({price:.2f}) >= EMA ({ema:.2f})")
        
        print(f"   SMA Condition: Fast < Slow? {sma_fast:.2f} < {sma_slow:.2f}? {'✅' if sma_fast < sma_slow else '❌'}")
        print(f"   Death Cross: {death_cross}")
        
        if not (death_cross or sma_fast < sma_slow):
            errors.append("SELL signal but neither death_cross nor SMA Fast < SMA Slow")
        
        # Validate SL/TP calculations for SELL
        expected_sl = price + (0.7 * atr)
        expected_tp = price - (2.5 * atr)
        
        print(f"\n💰 SL/TP Validation:")
        print(f"   Stop Loss: {sl:.2f} (expected: {expected_sl:.2f}) {'✅' if abs(sl - expected_sl) < 0.01 else '❌'}")
        print(f"   Take Profit: {tp:.2f} (expected: {expected_tp:.2f}) {'✅' if abs(tp - expected_tp) < 0.01 else '❌'}")
        
        if abs(sl - expected_sl) > 0.01:
            errors.append(f"SELL SL incorrect: {sl:.2f} vs expected {expected_sl:.2f}")
        if abs(tp - expected_tp) > 0.01:
            errors.append(f"SELL TP incorrect: {tp:.2f} vs expected {expected_tp:.2f}")
        
        # Check risk/reward
        risk = sl - price
        reward = price - tp
        rr_ratio = reward / risk if risk > 0 else 0
        
        print(f"   Risk: {risk:.2f} (SL above entry)")
        print(f"   Reward: {reward:.2f} (TP below entry)")
        print(f"   Risk/Reward: 1:{rr_ratio:.2f} (expected: ~1:3.57)")
        
        if rr_ratio < 3.0:
            warnings.append(f"Risk/Reward ratio ({rr_ratio:.2f}) is lower than expected (3.57)")
    
    elif direction == 'BUY':
        # BUY signal validation
        print(f"   Supertrend Check: {supertrend_dir} == 1? {'✅' if supertrend_dir == 1 else '❌'}")
        if supertrend_dir != 1:
            errors.append("BUY signal but supertrend is not UPTREND")
        
        print(f"   Price vs EMA: {price:.2f} > {ema:.2f}? {'✅' if price > ema else '❌'}")
        if price <= ema:
            errors.append(f"BUY signal but price ({price:.2f}) <= EMA ({ema:.2f})")
        
        print(f"   SMA Condition: Fast > Slow? {sma_fast:.2f} > {sma_slow:.2f}? {'✅' if sma_fast > sma_slow else '❌'}")
        print(f"   Golden Cross: {golden_cross}")
        
        if not (golden_cross or sma_fast > sma_slow):
            errors.append("BUY signal but neither golden_cross nor SMA Fast > SMA Slow")
        
        # Validate SL/TP calculations for BUY
        expected_sl = price - (0.7 * atr)
        expected_tp = price + (2.5 * atr)
        
        print(f"\n💰 SL/TP Validation:")
        print(f"   Stop Loss: {sl:.2f} (expected: {expected_sl:.2f}) {'✅' if abs(sl - expected_sl) < 0.01 else '❌'}")
        print(f"   Take Profit: {tp:.2f} (expected: {expected_tp:.2f}) {'✅' if abs(tp - expected_tp) < 0.01 else '❌'}")
        
        if abs(sl - expected_sl) > 0.01:
            errors.append(f"BUY SL incorrect: {sl:.2f} vs expected {expected_sl:.2f}")
        if abs(tp - expected_tp) > 0.01:
            errors.append(f"BUY TP incorrect: {tp:.2f} vs expected {expected_tp:.2f}")
        
        # Check risk/reward
        risk = price - sl
        reward = tp - price
        rr_ratio = reward / risk if risk > 0 else 0
        
        print(f"   Risk: {risk:.2f} (SL below entry)")
        print(f"   Reward: {reward:.2f} (TP above entry)")
        print(f"   Risk/Reward: 1:{rr_ratio:.2f} (expected: ~1:3.57)")
        
        if rr_ratio < 3.0:
            warnings.append(f"Risk/Reward ratio ({rr_ratio:.2f}) is lower than expected (3.57)")
    
    # Print results
    print(f"\n🔍 Validation Results:")
    if errors:
        print(f"   ❌ ERRORS: {len(errors)}")
        for error in errors:
            print(f"      - {error}")
    else:
        print(f"   ✅ All signal conditions validated")
    
    if warnings:
        print(f"   ⚠️  WARNINGS: {len(warnings)}")
        for warning in warnings:
            print(f"      - {warning}")
    
    return len(errors) == 0, errors, warnings


def main():
    """Main test function"""
    signal_file = '/Users/kirtanbhatt/code/stockScreener/cloud-function/data/signals/signals_20260310.jsonl'
    
    print("=" * 80)
    print("🧪 TESTING SAVED SIGNALS")
    print("=" * 80)
    print(f"\nReading signals from: {signal_file}")
    
    signals = load_signals(signal_file)
    print(f"Found {len(signals)} signals to validate\n")
    
    total_errors = 0
    total_warnings = 0
    passed = 0
    failed = 0
    
    for i, signal in enumerate(signals, 1):
        is_valid, errors, warnings = validate_signal(signal, i)
        
        if is_valid:
            passed += 1
        else:
            failed += 1
        
        total_errors += len(errors)
        total_warnings += len(warnings)
    
    # Summary
    print(f"\n\n{'='*80}")
    print("📋 TEST SUMMARY")
    print(f"{'='*80}")
    print(f"\nTotal Signals Tested: {len(signals)}")
    print(f"✅ Passed: {passed}")
    print(f"❌ Failed: {failed}")
    print(f"🚨 Total Errors: {total_errors}")
    print(f"⚠️  Total Warnings: {total_warnings}")
    
    if failed == 0:
        print(f"\n🎉 All signals validated successfully!")
        print(f"✅ Signal generation logic is working correctly")
    else:
        print(f"\n⚠️  Some signals have validation errors")
        print(f"🔍 Review the errors above to identify issues")
    
    print(f"\n{'='*80}\n")
    
    return failed == 0


if __name__ == "__main__":
    success = main()
    sys.exit(0 if success else 1)
