#!/usr/bin/env python3
"""
Setup script to configure local .env file for backtesting
Run this once to set up your Capital.com credentials
"""

import os
import json
import sys

def main():
    print("\n" + "="*70)
    print("🔧 Local Environment Setup for Backtesting")
    print("="*70)
    
    # Check if .env already exists
    if os.path.exists('.env'):
        print("\n⚠️  .env file already exists!")
        response = input("Do you want to overwrite it? (y/n): ").strip().lower()
        if response != 'y':
            print("Aborted. Keeping existing .env file.")
            return
    
    print("\n📝 This script will help you create a .env file with Capital.com credentials")
    print("   You can use either DEMO or LIVE account credentials")
    print("   (DEMO is recommended for backtesting)\n")
    
    # Collect credentials
    print("Enter your Capital.com credentials:")
    print("(Press Ctrl+C to cancel at any time)\n")
    
    try:
        apikey = input("API Key (for webhook validation): ").strip()
        username = input("Capital.com Username/Email: ").strip()
        password = input("Capital.com Password: ").strip()
        capkey = input("Capital.com API Key (from developer portal): ").strip()
        
        if not all([apikey, username, password, capkey]):
            print("\n❌ All fields are required!")
            return
        
        # Create credentials JSON
        credentials = {
            "apikey": apikey,
            "username": username,
            "password": password,
            "capkey": capkey
        }
        
        credentials_json = json.dumps(credentials)
        
        # Create .env file
        env_content = f"""# Capital.com API Credentials
# Generated by setup_local_env.py

apicredentials={credentials_json}

# Optional: Enable debug logging
# DEBUG=true

# Optional: Use live environment (default is demo)
# CAPITAL_ENV=live
# ALLOW_LIVE_TRADING=true
"""
        
        with open('.env', 'w') as f:
            f.write(env_content)
        
        print("\n" + "="*70)
        print("✅ Successfully created .env file!")
        print("="*70)
        print("\n📁 Created: .env")
        print("\n🚀 You can now run backtests:")
        print("   python3 src/run_backtest.py")
        print("   python3 src/strategy.py")
        print("   python3 src/market_data.py")
        print("\n⚠️  IMPORTANT: Never commit .env to version control!")
        print("   (It's already in .gitignore)\n")
        
    except KeyboardInterrupt:
        print("\n\n❌ Setup cancelled by user")
        sys.exit(1)
    except Exception as e:
        print(f"\n❌ Error: {e}")
        sys.exit(1)


if __name__ == '__main__':
    main()
