cd /Users/kirtanbhatt/code/stockScreener/cloud-function && python3 scripts/run-local-optimization.py \
  --data-file data/GOLD_M5_150000bars.csv \
  --instrument GOLD \
  --timeframe M5 \
  --mode short \
  --st-mult 2.0 \
  --sma-fast 25 \
  --sma-slow 30 \
  --sl-pips 10 \
  --tp-pips 40 \
  --pip-value 1.0 \
  --fixed-only \
  --enable-event-blocking \
  --capital 10000 2>&1